####################################################################################
#server yaml
####################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - image: gcr.io/devops-nodejs/devops-demo-server:vBUILD_NUMBER
        resources: {}
